### ISSUE TITLE
Audit use of Feature content CSS and remove if possible

### ISSUE THREAD

**Issue by mchelen-gov** [department-of-veterans-affairs/vets-design-system-documentation#195]
**Describe the bug**
When using `feature` class from https://design.va.gov/components/featured-content any `<p>` child elements have their font and color overridden using `!important`. This means developers also have to use `!important` on their styling of this tag within a `feature` element or it will be overridden.

**To Reproduce**

`style.scss` includes this CSS:
```css
  .feature p {
    color: inherit !important;
    font: inherit !important;
}
```

Example app HTML:
```html
<div class="feature">
  <h3>If I’m a Veteran, can I use this app?</h3>
  <p style="myClass">You may be able to use this app if you are Veteran.</p>
</div>
```

Example app CSS/SASS:
```css
.myClass {
  font-weight: bold;
}
```

**Expected behavior**
Normally a developer would expect the `<p>` to become styled with `font-weight: bold;`  however this will be overridden by the `feature` class font settings.
