### ISSUE TITLE
checkbox text overflow

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/vets-design-system-documentation#2830]
# Bug Report

- [x] I’ve searched for any related issues and avoided creating a duplicate issue.

## What happened

While testing long checkbox labels, the text does not wrap and overflows off the screen. This also happens for the description, error and hint text (see screenshot)
<img width="778" alt="va-checkbox with very long label, description, error and hint text. All of which are overflowing offscreen" src="https://github.com/department-of-veterans-affairs/vets-design-system-documentation/assets/136959/4b860f16-1ee7-4a7c-91cf-6c2c2acb7efc">

## What I expected to happen

Long text to wrap

Possible fix:

```css
.usa-legend,
.usa-hint,
#checkbox-error-message,
.usa-checkbox__label {
  overflow-wrap: break-word;
}

.usa-hint,
#checkbox-error-message {
  max-width: 480px;
  display: block; /* or change these spans into divs */
}
```

<details><summary>Result</summary>

<img width="576" alt="va-checkbox with wrapping label, hint, description and error message" src="https://github.com/department-of-veterans-affairs/vets-design-system-documentation/assets/136959/0c1f93a0-605c-4813-b10a-fbedeb4bb69f"></details>

## Reproducing

- Formation version: All
- Device: (e.g. iPhone 8, Macbook) All
- Browser: (e.g. Firefox, IE 11) All

Steps to reproduce:

1. Go to [checkbox storybook](https://design.va.gov/storybook/?path=/docs/uswds-va-checkbox--default)
2. Enter long label text
3. Enter long error message
4. Enter long description text
5. Enter long hint text

## Urgency

How urgent is this request? Please select the appropriate option below and/or provide details

- [ ] This bug is blocking work currently in progress
- [x] This bug is affecting work currently in progress but we have a workaround
- [ ] This bug is blocking work planned within the next few sprints
- [ ] This bug is not blocking any work
- [ ] Other

### Details

Only able to fix the checkbox label using `::part(label)`, but we don't have an excessively long description, hint or error message, so this isn't urgent.
