### ISSUE TITLE
No disabled appearance for green primary button

### ISSUE THREAD

**Issue by Mottie** [department-of-veterans-affairs/vets-design-system-documentation#343]
# Bug Report

- [x] I’ve searched for any related issues and avoided creating a duplicate issue.

## What happened

Green [primary buttons](https://design.va.gov/components/buttons#primary-buttons) require two class names to apply the style: `usa-button-primary` and `va-button-primary`

- `usa-button-primary` defines a blue button style
- `va-button-primary` defines the green button color style, but is set using an `!important` flag - this causes the `disabled` state of that button to not _look_ disabled ([reference](https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/blob/master/packages/formation/sass/base/_va.scss#L1055-L1062))

   ```css
    .va-button-primary {
    background: $color-green !important;
  
    &:hover,
    &:focus {
      background-color: $color-green-darker !important;
      text-decoration: none !important;
    }
   ```

I don't think we include any disabled primary buttons on the va.gov site, but I think this still needs to be addressed.

## What I expected to happen

A disabled `va-button-primary` should become grayed-out similar to all the other disabled button styles

## Reproducing
- Formation version: All
- Device: (e.g. iPhone 8, Macbook): All
- Browser: (e.g. Firefox, IE 11): All

Steps to reproduce:

1. Go to https://design.va.gov/components/buttons#primary-buttons
2. Open the dev console - press <kbd>F12</kbd>, or right click on the page and choose "Inspect"
3. Choose "Console" tab
4. Enter `$('.va-button-primary').disabled = true;` into the console and press <kbd>Enter</kbd>
5. Hover over the first green "Button"... you'll notice that hovering it no longer changes the styling. It's disabled, but still green
